name: chandoiqua
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'







dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  firebase_storage: ^11.7.4
  fpdart: ^1.1.0
  uuid: ^4.4.0
  either_dart: ^1.0.0
  buttons_tabbar: ^1.3.7+1
  group_list_view: ^1.1.1
  google_maps_flutter: ^2.6.0
  flutter_config: ^2.0.2
  icons_plus: ^4.0.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  http: ^1.2.1
  slider_button: ^2.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_bloc: ^8.1.4
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  googleapis_auth: ^1.5.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_secure_storage: ^4.2.1
  get: ^4.6.6
  carousel_slider: ^4.2.1
  rxdart: ^0.27.7
  retrofit: ^4.1.0
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  sqflite: ^2.3.2
  logger: ^2.1.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.1
  custom_date_range_picker: ^1.0.10
  flutter_sequence_animation: ^4.0.0
  convex_bottom_bar: ^3.2.0
  custom_navigation_bar: ^0.8.2
  dots_indicator: ^3.0.0
  crypto: ^3.0.3
  sprintf: ^7.0.0
  flutter_dash: ^1.0.0
  flutter_stripe: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  retrofit_generator: ^8.1.0
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1




flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/bg1.png
    - assets/images/backgroud.png
    - assets/logos/google_logo.png
    - assets/images/google_logo.png
    - assets/images/bgtour.jpeg
    - assets/images/IMG_7985.png
    - assets/images/booknowbutton.png
    - assets/locations.json
    - assets/images/MoMo_Logo.png
    - assets/images/paypal.jpg
    - assets/images/paypalll.jpg
    - assets/images/dn1.jpeg
    - assets/images/dn2.jpg
    - assets/images/dn3.jpg
    - assets/images/amazon.png
    - assets/images/creditcard.jpg
    - assets/images/ggpay.png
    - assets/images/vlh-1581501483279773323335.jpg
    - assets/app_icon/iconapp.jpg

flutter_gen:
  output: lib/constants/resources/gen/
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors/colors.xml
flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_foreground: "assets/app_icon/iconapp.jpg"
  adaptive_icon_background: "#233BA4"
  ios: true
  image_path: "assets/app_icon/iconapp.jpg"


  
  
  
  
  
      
  
  
  
  
  
  
  
  
  
  
  
  
  
