name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'  # Hoặc phiên bản Flutter bạn đang dùng

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze Dart code
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build release APK
      run: flutter build apk --release

    - name: Upload release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
